[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npx prisma migrate deploy"

[deploy]
startCommand = "node api/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
